"""Initial PetCare persistence schema."""

from __future__ import annotations

from alembic import op


revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


SCHEMA_STATEMENTS = [
    "CREATE TABLE cameras (\n\tcamera_id VARCHAR(32) NOT NULL, \n\tstatus VARCHAR(8) DEFAULT 'offline' NOT NULL, \n\tlast_frame_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tCONSTRAINT pk_cameras PRIMARY KEY (camera_id), \n\tCONSTRAINT ck_cameras_camera_id CHECK (camera_id='pc-webcam-01'), \n\tCONSTRAINT ck_cameras_status CHECK (status IN ('online','offline'))\n)",
    "CREATE TABLE devices (\n\tdevice_id VARCHAR(32) NOT NULL, \n\tstatus VARCHAR(8) DEFAULT 'unknown' NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tCONSTRAINT pk_devices PRIMARY KEY (device_id), \n\tCONSTRAINT ck_devices_device_id CHECK (device_id IN ('entrance-01','petzone-01')), \n\tCONSTRAINT ck_devices_status CHECK (status IN ('online','offline','unknown'))\n)",
    "CREATE TABLE zones (\n\tzone_name VARCHAR(32) NOT NULL, \n\tx1 INTEGER NOT NULL, \n\ty1 INTEGER NOT NULL, \n\tx2 INTEGER NOT NULL, \n\ty2 INTEGER NOT NULL, \n\tenabled BOOLEAN DEFAULT TRUE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tCONSTRAINT pk_zones PRIMARY KEY (zone_name), \n\tCONSTRAINT ck_zones_zone_name CHECK (zone_name IN ('food_bowl','pet_bed')), \n\tCONSTRAINT ck_zones_x_bounds CHECK (0<=x1 AND x1<x2 AND x2<=640), \n\tCONSTRAINT ck_zones_y_bounds CHECK (0<=y1 AND y1<y2 AND y2<=480)\n)",
    "CREATE TABLE bed_calibrations (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tdevice_id VARCHAR(32) NOT NULL, \n\tcalibrated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\twindow_start TIMESTAMP WITH TIME ZONE NOT NULL, \n\twindow_end TIMESTAMP WITH TIME ZONE NOT NULL, \n\tleft_sample_count SMALLINT NOT NULL, \n\tleft_baseline DOUBLE PRECISION NOT NULL, \n\tleft_polarity SMALLINT NOT NULL, \n\tleft_stability_limit SMALLINT NOT NULL, \n\tcenter_sample_count SMALLINT NOT NULL, \n\tcenter_baseline DOUBLE PRECISION NOT NULL, \n\tcenter_polarity SMALLINT NOT NULL, \n\tcenter_stability_limit SMALLINT NOT NULL, \n\tright_sample_count SMALLINT NOT NULL, \n\tright_baseline DOUBLE PRECISION NOT NULL, \n\tright_polarity SMALLINT NOT NULL, \n\tright_stability_limit SMALLINT NOT NULL, \n\tentry_threshold INTEGER NOT NULL, \n\texit_threshold INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tCONSTRAINT pk_bed_calibrations PRIMARY KEY (id), \n\tCONSTRAINT ck_bed_calibrations_device_id CHECK (device_id='petzone-01'), \n\tCONSTRAINT ck_bed_calibrations_window CHECK (window_end=window_start+INTERVAL '60 seconds' AND calibrated_at>=window_end), \n\tCONSTRAINT ck_bed_calibrations_sample_counts CHECK (left_sample_count>=45 AND center_sample_count>=45 AND right_sample_count>=45), \n\tCONSTRAINT ck_bed_calibrations_baselines CHECK (left_baseline BETWEEN 0 AND 4095 AND left_baseline > '-Infinity'::DOUBLE PRECISION AND left_baseline < 'Infinity'::DOUBLE PRECISION AND center_baseline BETWEEN 0 AND 4095 AND center_baseline > '-Infinity'::DOUBLE PRECISION AND center_baseline < 'Infinity'::DOUBLE PRECISION AND right_baseline BETWEEN 0 AND 4095 AND right_baseline > '-Infinity'::DOUBLE PRECISION AND right_baseline < 'Infinity'::DOUBLE PRECISION), \n\tCONSTRAINT ck_bed_calibrations_polarities CHECK (left_polarity IN (-1,1) AND center_polarity IN (-1,1) AND right_polarity IN (-1,1)), \n\tCONSTRAINT ck_bed_calibrations_stability_limits CHECK (left_stability_limit BETWEEN 0 AND 4095 AND center_stability_limit BETWEEN 0 AND 4095 AND right_stability_limit BETWEEN 0 AND 4095), \n\tCONSTRAINT ck_bed_calibrations_thresholds CHECK (0<=exit_threshold AND exit_threshold<entry_threshold AND entry_threshold<=12285), \n\tCONSTRAINT uq_bed_calibrations_device_calibrated UNIQUE (device_id, calibrated_at), \n\tCONSTRAINT fk_bed_calibrations_device_id_devices FOREIGN KEY(device_id) REFERENCES devices (device_id) ON DELETE RESTRICT\n)",
    "CREATE INDEX ix_bed_calibrations_device_time ON bed_calibrations (device_id, calibrated_at DESC, id DESC)",
    "CREATE TABLE camera_events (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcamera_id VARCHAR(32) NOT NULL, \n\tsubject_id VARCHAR(16), \n\tdetected_type VARCHAR(16) NOT NULL, \n\tconfidence DOUBLE PRECISION NOT NULL, \n\tbbox_x INTEGER NOT NULL, \n\tbbox_y INTEGER NOT NULL, \n\tbbox_width INTEGER NOT NULL, \n\tbbox_height INTEGER NOT NULL, \n\tcenter_x INTEGER NOT NULL, \n\tcenter_y INTEGER NOT NULL, \n\tzone_name VARCHAR(32), \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tCONSTRAINT pk_camera_events PRIMARY KEY (id), \n\tCONSTRAINT ck_camera_events_detected_type CHECK (detected_type IN ('person','dog','cat')), \n\tCONSTRAINT ck_camera_events_subject_type CHECK (((detected_type='person' AND subject_id IS NULL) OR (detected_type='dog' AND subject_id='dog_001') OR (detected_type='cat' AND subject_id='cat_001')) IS TRUE), \n\tCONSTRAINT ck_camera_events_confidence CHECK (confidence > '-Infinity'::DOUBLE PRECISION AND confidence < 'Infinity'::DOUBLE PRECISION AND confidence BETWEEN 0 AND 1), \n\tCONSTRAINT ck_camera_events_bbox_x CHECK (0<=bbox_x AND bbox_x<bbox_x+bbox_width AND bbox_x+bbox_width<=640), \n\tCONSTRAINT ck_camera_events_bbox_y CHECK (0<=bbox_y AND bbox_y<bbox_y+bbox_height AND bbox_y+bbox_height<=480), \n\tCONSTRAINT ck_camera_events_center CHECK (bbox_x<=center_x AND center_x<bbox_x+bbox_width AND bbox_y<=center_y AND center_y<bbox_y+bbox_height), \n\tCONSTRAINT uq_camera_events_camera_type_observed UNIQUE (camera_id, detected_type, observed_at), \n\tCONSTRAINT fk_camera_events_camera_id_cameras FOREIGN KEY(camera_id) REFERENCES cameras (camera_id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_camera_events_zone_name_zones FOREIGN KEY(zone_name) REFERENCES zones (zone_name) ON DELETE SET NULL\n)",
    "CREATE INDEX ix_camera_events_camera_time ON camera_events (camera_id, observed_at DESC, id DESC)",
    "CREATE INDEX ix_camera_events_zone_type_time ON camera_events (zone_name, detected_type, observed_at DESC, id DESC)",
    "CREATE TABLE sensor_readings (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tdevice_id VARCHAR(32) NOT NULL, \n\tsensor_type VARCHAR(32) NOT NULL, \n\tvalue_number DOUBLE PRECISION, \n\tvalue_boolean BOOLEAN, \n\tunit VARCHAR(8) NOT NULL, \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tCONSTRAINT pk_sensor_readings PRIMARY KEY (id), \n\tCONSTRAINT ck_sensor_readings_one_value CHECK ((value_number IS NULL) <> (value_boolean IS NULL)), \n\tCONSTRAINT ck_sensor_readings_finite_number CHECK (value_number IS NULL OR (value_number > '-Infinity'::DOUBLE PRECISION AND value_number < 'Infinity'::DOUBLE PRECISION)), \n\tCONSTRAINT ck_sensor_readings_type_unit_value CHECK ((sensor_type='temperature' AND unit='C' AND value_number IS NOT NULL AND value_boolean IS NULL) OR (sensor_type='humidity' AND unit='%' AND value_number IS NOT NULL AND value_boolean IS NULL) OR (sensor_type IN ('presence_moving','presence_stationary') AND unit='bool' AND value_number IS NULL AND value_boolean IS NOT NULL) OR (sensor_type IN ('food_weight','water_weight') AND device_id='petzone-01' AND unit='g' AND value_number IS NOT NULL AND value_boolean IS NULL) OR (sensor_type IN ('bed_pressure_left','bed_pressure_center','bed_pressure_right') AND device_id='petzone-01' AND unit='adc' AND value_number IS NOT NULL AND value_boolean IS NULL)), \n\tCONSTRAINT ck_sensor_readings_device_profile CHECK (device_id='petzone-01' OR sensor_type IN ('temperature','humidity','presence_moving','presence_stationary')), \n\tCONSTRAINT ck_sensor_readings_pressure_range CHECK (sensor_type NOT IN ('bed_pressure_left','bed_pressure_center','bed_pressure_right') OR (value_number BETWEEN 0 AND 4095 AND value_number=trunc(value_number))), \n\tCONSTRAINT uq_sensor_readings_device_type_observed UNIQUE (device_id, sensor_type, observed_at), \n\tCONSTRAINT fk_sensor_readings_device_id_devices FOREIGN KEY(device_id) REFERENCES devices (device_id) ON DELETE RESTRICT\n)",
    "CREATE INDEX ix_sensor_readings_device_type_time ON sensor_readings (device_id, sensor_type, observed_at DESC, id DESC)",
    "CREATE INDEX ix_sensor_readings_type_time ON sensor_readings (sensor_type, observed_at DESC, id DESC)",
    "CREATE TABLE behavior_events (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tsubject_id VARCHAR(16) NOT NULL, \n\tbehavior_type VARCHAR(16) NOT NULL, \n\tsource_camera_event_id BIGINT NOT NULL, \n\tsource_sensor_reading_id BIGINT NOT NULL, \n\tsource_key VARCHAR(160) NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tended_at TIMESTAMP WITH TIME ZONE, \n\tduration_seconds INTEGER, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tCONSTRAINT pk_behavior_events PRIMARY KEY (id), \n\tCONSTRAINT ck_behavior_events_subject_id CHECK (subject_id IN ('dog_001','cat_001')), \n\tCONSTRAINT ck_behavior_events_behavior_type CHECK (behavior_type IN ('eating','resting')), \n\tCONSTRAINT ck_behavior_events_open_closed CHECK ((ended_at IS NULL AND duration_seconds IS NULL) OR (ended_at IS NOT NULL AND duration_seconds IS NOT NULL AND ended_at>=started_at AND duration_seconds>=0)), \n\tCONSTRAINT uq_behavior_events_source_key UNIQUE (source_key), \n\tCONSTRAINT fk_behavior_events_source_camera_event_id_camera_events FOREIGN KEY(source_camera_event_id) REFERENCES camera_events (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_behavior_events_source_sensor_reading_id_sensor_readings FOREIGN KEY(source_sensor_reading_id) REFERENCES sensor_readings (id) ON DELETE RESTRICT\n)",
    "CREATE INDEX ix_behavior_events_subject_type_time ON behavior_events (subject_id, behavior_type, started_at DESC, id DESC)",
    "CREATE INDEX ix_behavior_events_time ON behavior_events (started_at DESC, id DESC)",
    "CREATE UNIQUE INDEX uq_behavior_events_one_open_per_type ON behavior_events (behavior_type) WHERE ended_at IS NULL",
    "CREATE TABLE anomaly_events (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tsubject_id VARCHAR(16), \n\tanomaly_type VARCHAR(32) NOT NULL, \n\tseverity VARCHAR(8) DEFAULT 'warning' NOT NULL, \n\tmismatch_kind VARCHAR(32), \n\tsource_behavior_event_id BIGINT, \n\tsource_key VARCHAR(160) NOT NULL, \n\tmessage TEXT NOT NULL, \n\toccurred_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tCONSTRAINT pk_anomaly_events PRIMARY KEY (id), \n\tCONSTRAINT ck_anomaly_events_anomaly_type CHECK (anomaly_type IN ('no_meal_12h','bed_sensor_mismatch')), \n\tCONSTRAINT ck_anomaly_events_severity CHECK (severity='warning'), \n\tCONSTRAINT ck_anomaly_events_relation CHECK (((anomaly_type='no_meal_12h' AND subject_id IN ('dog_001','cat_001') AND mismatch_kind IS NULL AND source_behavior_event_id IS NOT NULL) OR (anomaly_type='bed_sensor_mismatch' AND mismatch_kind='sensor_check' AND subject_id IN ('dog_001','cat_001') AND source_behavior_event_id IS NULL) OR (anomaly_type='bed_sensor_mismatch' AND mismatch_kind='unconfirmed_pressure' AND subject_id IS NULL AND source_behavior_event_id IS NULL)) IS TRUE), \n\tCONSTRAINT ck_anomaly_events_message CHECK (length(message)>0), \n\tCONSTRAINT uq_anomaly_events_source_key UNIQUE (source_key), \n\tCONSTRAINT fk_anomaly_events_source_behavior_event_id_behavior_events FOREIGN KEY(source_behavior_event_id) REFERENCES behavior_events (id) ON DELETE RESTRICT\n)",
    "CREATE INDEX ix_anomaly_events_subject_type_time ON anomaly_events (subject_id, anomaly_type, occurred_at DESC, id DESC)",
    "CREATE INDEX ix_anomaly_events_time ON anomaly_events (occurred_at DESC, id DESC)",
    "CREATE TABLE rest_sessions (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tsubject_id VARCHAR(16) NOT NULL, \n\tbehavior_event_id BIGINT NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_confirmed_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tended_at TIMESTAMP WITH TIME ZONE, \n\tduration_seconds INTEGER, \n\tclose_reason VARCHAR(24), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tCONSTRAINT pk_rest_sessions PRIMARY KEY (id), \n\tCONSTRAINT ck_rest_sessions_subject_id CHECK (subject_id IN ('dog_001','cat_001')), \n\tCONSTRAINT ck_rest_sessions_last_confirmed CHECK (last_confirmed_at>=started_at), \n\tCONSTRAINT ck_rest_sessions_open_closed CHECK ((ended_at IS NULL AND duration_seconds IS NULL AND close_reason IS NULL) OR (ended_at IS NOT NULL AND duration_seconds IS NOT NULL AND close_reason IS NOT NULL AND ended_at>=started_at AND duration_seconds>=0 AND close_reason IN ('pressure_exit','camera_exit','sensor_loss','camera_loss','shutdown','restart'))), \n\tCONSTRAINT uq_rest_sessions_behavior_event_id UNIQUE (behavior_event_id), \n\tCONSTRAINT fk_rest_sessions_behavior_event_id_behavior_events FOREIGN KEY(behavior_event_id) REFERENCES behavior_events (id) ON DELETE RESTRICT\n)",
    "CREATE INDEX ix_rest_sessions_end_time ON rest_sessions (ended_at DESC, id DESC)",
    "CREATE INDEX ix_rest_sessions_subject_time ON rest_sessions (subject_id, started_at DESC, id DESC)",
    "CREATE UNIQUE INDEX uq_rest_sessions_one_open ON rest_sessions ((1)) WHERE ended_at IS NULL"
]
DROP_TABLES = [
    "rest_sessions",
    "anomaly_events",
    "behavior_events",
    "sensor_readings",
    "camera_events",
    "bed_calibrations",
    "zones",
    "devices",
    "cameras"
]


ANOMALY_FUNCTION = """
CREATE FUNCTION ck_anomaly_source_behavior() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM anomaly_events a
    LEFT JOIN behavior_events b ON b.id = a.source_behavior_event_id
    WHERE (a.anomaly_type = 'no_meal_12h' AND (b.id IS NULL OR b.behavior_type <> 'eating' OR b.subject_id <> a.subject_id))
       OR (a.anomaly_type = 'bed_sensor_mismatch' AND a.source_behavior_event_id IS NOT NULL)
  ) THEN
    RAISE EXCEPTION 'anomaly source behavior contract violated' USING ERRCODE = '23514';
  END IF;
  RETURN NULL;
END;
$$
"""


REST_FUNCTION = """
CREATE FUNCTION ck_rest_session_behavior() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM rest_sessions r
    LEFT JOIN behavior_events b ON b.id = r.behavior_event_id
    WHERE b.id IS NULL
       OR b.behavior_type <> 'resting'
       OR b.subject_id <> r.subject_id
       OR b.started_at IS DISTINCT FROM r.started_at
       OR b.ended_at IS DISTINCT FROM r.ended_at
       OR b.duration_seconds IS DISTINCT FROM r.duration_seconds
  ) OR EXISTS (
    SELECT 1
    FROM behavior_events b
    LEFT JOIN rest_sessions r ON r.behavior_event_id = b.id
    WHERE b.behavior_type = 'resting'
    GROUP BY b.id
    HAVING count(r.id) <> 1
  ) THEN
    RAISE EXCEPTION 'rest session behavior contract violated' USING ERRCODE = '23514';
  END IF;
  RETURN NULL;
END;
$$
"""


def upgrade() -> None:
    for statement in SCHEMA_STATEMENTS:
        op.execute(statement)
    op.execute(
        "INSERT INTO zones(zone_name,x1,y1,x2,y2,enabled) VALUES "
        "('food_bowl',40,260,260,470,TRUE),"
        "('pet_bed',320,180,630,470,TRUE)"
    )
    op.execute(ANOMALY_FUNCTION)
    op.execute(REST_FUNCTION)
    for table in ("anomaly_events", "behavior_events"):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER ck_anomaly_source_behavior AFTER INSERT OR UPDATE OR DELETE ON {table} "
            "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION ck_anomaly_source_behavior()"
        )
    for table in ("rest_sessions", "behavior_events"):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER ck_rest_session_behavior AFTER INSERT OR UPDATE OR DELETE ON {table} "
            "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION ck_rest_session_behavior()"
        )


def downgrade() -> None:
    for table in ("behavior_events", "rest_sessions"):
        op.execute(f"DROP TRIGGER IF EXISTS ck_rest_session_behavior ON {table}")
    for table in ("behavior_events", "anomaly_events"):
        op.execute(f"DROP TRIGGER IF EXISTS ck_anomaly_source_behavior ON {table}")
    op.execute("DROP FUNCTION IF EXISTS ck_rest_session_behavior()")
    op.execute("DROP FUNCTION IF EXISTS ck_anomaly_source_behavior()")
    for table in DROP_TABLES:
        op.execute(f"DROP TABLE {table}")
