"""Add the durable Jetson clip-trigger outbox."""

from __future__ import annotations

from alembic import op


revision = "0002_clip_trigger_outbox"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


CREATE_TABLE = """
CREATE TABLE clip_trigger_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_type VARCHAR(32) NOT NULL,
    event_id BIGINT NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deadline_at TIMESTAMP WITH TIME ZONE NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    attempts INTEGER NOT NULL,
    last_error VARCHAR(64),
    remote_boot_id VARCHAR(32),
    remote_command_id VARCHAR(32),
    put_started_at TIMESTAMP WITH TIME ZONE,
    accepted_at TIMESTAMP WITH TIME ZONE,
    processed_at TIMESTAMP WITH TIME ZONE,
    terminal_reason VARCHAR(32),
    CONSTRAINT pk_clip_trigger_outbox PRIMARY KEY (id),
    CONSTRAINT ck_clip_trigger_outbox_event_type CHECK (event_type IN ('eating','resting','bed_sensor_mismatch')),
    CONSTRAINT ck_clip_trigger_outbox_event_id CHECK (event_id > 0),
    CONSTRAINT ck_clip_trigger_outbox_deadline CHECK (deadline_at=created_at+INTERVAL '3 seconds'),
    CONSTRAINT ck_clip_trigger_outbox_attempts CHECK (attempts >= 0),
    CONSTRAINT ck_clip_trigger_outbox_remote_boot_id CHECK (remote_boot_id IS NULL OR remote_boot_id ~ '^[0-9a-f]{32}$'),
    CONSTRAINT ck_clip_trigger_outbox_remote_command_id CHECK (remote_command_id IS NULL OR remote_command_id ~ '^[0-9a-f]{32}$'),
    CONSTRAINT ck_clip_trigger_outbox_accepted_identity CHECK ((remote_boot_id IS NULL)=(accepted_at IS NULL) AND (accepted_at IS NULL OR remote_command_id IS NOT NULL)),
    CONSTRAINT ck_clip_trigger_outbox_accepted_window CHECK (accepted_at IS NULL OR (accepted_at>=created_at-INTERVAL '200 milliseconds' AND accepted_at<=deadline_at)),
    CONSTRAINT ck_clip_trigger_outbox_accepted_put CHECK (accepted_at IS NULL OR put_started_at IS NOT NULL),
    CONSTRAINT ck_clip_trigger_outbox_last_error CHECK (last_error IS NULL OR last_error ~ '^[a-z0-9_]{1,64}$'),
    CONSTRAINT ck_clip_trigger_outbox_put_command CHECK (put_started_at IS NULL OR remote_command_id IS NOT NULL),
    CONSTRAINT ck_clip_trigger_outbox_put_window CHECK (put_started_at IS NULL OR (put_started_at>=created_at AND put_started_at<deadline_at)),
    CONSTRAINT ck_clip_trigger_outbox_terminal_reason CHECK (terminal_reason IS NULL OR terminal_reason='clip_missed'),
    CONSTRAINT ck_clip_trigger_outbox_accepted_terminal CHECK (accepted_at IS NULL OR terminal_reason IS NULL OR last_error='clip_gone'),
    CONSTRAINT ck_clip_trigger_outbox_terminal_processed CHECK (terminal_reason IS NULL OR processed_at IS NOT NULL),
    CONSTRAINT ck_clip_trigger_outbox_processed_state CHECK (processed_at IS NULL OR accepted_at IS NOT NULL OR terminal_reason IS NOT NULL),
    CONSTRAINT uq_clip_trigger_outbox_event_type_event_id UNIQUE (event_type, event_id)
)
"""


def upgrade() -> None:
    op.execute(CREATE_TABLE)
    op.execute("CREATE INDEX ix_clip_trigger_outbox_due ON clip_trigger_outbox (next_attempt_at, id) WHERE processed_at IS NULL")
    op.execute("CREATE UNIQUE INDEX uq_clip_trigger_outbox_remote_command_id ON clip_trigger_outbox (remote_command_id) WHERE remote_command_id IS NOT NULL")


def downgrade() -> None:
    op.execute("DROP TABLE clip_trigger_outbox")
