"""Add activity observations."""

from __future__ import annotations

from alembic import op


revision = "0003_activity_observations"
down_revision = "0002_clip_trigger_outbox"
branch_labels = None
depends_on = None


CREATE_TABLE = """
CREATE TABLE activity_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    camera_id VARCHAR(32) NOT NULL,
    subject_id VARCHAR(16) NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    center_x INTEGER NOT NULL,
    center_y INTEGER NOT NULL,
    moving BOOLEAN NOT NULL,
    distance DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_activity_observations PRIMARY KEY (id),
    CONSTRAINT ck_activity_observations_camera_id CHECK (camera_id='pc-webcam-01'),
    CONSTRAINT ck_activity_observations_subject_id CHECK (subject_id IN ('dog_001','cat_001')),
    CONSTRAINT ck_activity_observations_observed_at_second CHECK (observed_at=date_trunc('second', observed_at)),
    CONSTRAINT ck_activity_observations_center_x CHECK (0<=center_x AND center_x<640),
    CONSTRAINT ck_activity_observations_center_y CHECK (0<=center_y AND center_y<480),
    CONSTRAINT ck_activity_observations_distance CHECK (distance>=0 AND distance > '-Infinity'::DOUBLE PRECISION AND distance < 'Infinity'::DOUBLE PRECISION),
    CONSTRAINT uq_activity_observations_camera_subject_observed UNIQUE (camera_id, subject_id, observed_at),
    CONSTRAINT fk_activity_observations_camera_id_cameras FOREIGN KEY(camera_id) REFERENCES cameras (camera_id) ON DELETE RESTRICT
)
"""


def upgrade() -> None:
    op.execute(CREATE_TABLE)
    op.execute("CREATE INDEX ix_activity_observations_subject_time ON activity_observations (subject_id, observed_at DESC, id DESC)")


def downgrade() -> None:
    op.execute("DROP TABLE activity_observations")
